version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-nginx
    ports:
      - '8080:80'
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh && npm start
    networks:
      - node-nginx
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nodedb

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-nginx

networks:
  node-nginx:
    driver: bridge
