apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: "goserver"
          image: "andersonfpcorrea/hello-go:v11"
          # vCPU -> 1000m (milicores) = 1 CPU1
          resources:
            requests: # min resources. If not available, the pod will not be scheduled
              cpu: "0.05" # 300m or 0.3 (milicores)
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            # initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 1

          livenessProbe: # watch -n1 kubectl get pods
            httpGet:
              path: /healthz
              port: 8080
            # initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: /go/myfamily
              name: config
              readOnly: true
            - mountPath: "/go/pvc"
              name: goserver-volume
      volumes:
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt
          # env:
          #   - name: "NAME"
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: "AGE"
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE
