apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goserver-pvc
spec:
  accessModes:
    - ReadWriteOnce # Pods can read and write to the volume in the same node
  resources:
    requests:
      storage: 1Gi
    # - ReadWriteMany
    # - ReadOnlyMany
    # - ReadWriteOnce
  # storageClassName: local-storage
