apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  USER: YW5kZXJzb24K # anderson in base64: `echo "anderson" | base64`
  PASSWORD: MTIzNDU2Cg== # 123456 in base64: `echo "123456" | base64`
# To decode base64: `echo "YW5kZXJzb24K" | base64 --decode`
